[project]
name = "workflow"
version = "0.1.0"
description = "Example usage of the Render Tasks Python SDK"
requires-python = ">=3.12"
dependencies = [
    "render-sdk",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]

[tool.uv.sources]
render-sdk = { path = "render_sdk-0.7.0-py3-none-any.whl" }
