previewsEnabled: true
services:
  - type: web
    name: test-invalid-env-var
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: "."
        value: " bar"
      - fromGroup: prod-group