previewsEnabled: true
services:
  - type: web
    name: test-invalid-env-var
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: "2"
        value: invalid-env-var-value
